// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Protobuf.Protocol {

  /// <summary>Holder for reflection information generated from Enum.proto</summary>
  public static partial class EnumReflection {

    #region Descriptor
    /// <summary>File descriptor for Enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpFbnVtLnByb3RvEghQcm90b2NvbCrDBAoFTXNnSWQSCwoHQ19IRUxMTxAA",
            "EgsKB1NfSEVMTE8QARIQCgxDX0hFTExPX0RPTkUQAhIQCgxTX0hFTExPX0RP",
            "TkUQAxIOCgpDX1JFR0lTVEVSEAQSDgoKU19SRUdJU1RFUhAFEgsKB0NfTE9H",
            "SU4QBhILCgdTX0xPR0lOEAcSEAoMQ19FTlRFUl9ST09NEAgSEAoMU19FTlRF",
            "Ul9ST09NEAkSDwoLQ19FTlRFUl9NQVAQChIPCgtTX0VOVEVSX01BUBALEhkK",
            "FVNfRU5URVJfTUFQX0JST0FEQ0FTVBAMEhAKDENfTEVBVkVfUk9PTRANEhAK",
            "DFNfTEVBVkVfUk9PTRAOEg8KC0NfTEVBVkVfTUFQEA8SDwoLU19MRUFWRV9N",
            "QVAQEBIKCgZDX0NIQVQQERIKCgZTX0NIQVQQEhIQCgxDX01PVkVfU1RBUlQQ",
            "ExIQCgxTX01PVkVfU1RBUlQQFBIMCghDX01PVklORxAVEgwKCFNfTU9WSU5H",
            "EBYSDgoKQ19NT1ZFX0VORBAXEg4KClNfTU9WRV9FTkQQGBIKCgZDX0pVTVAQ",
            "GRIKCgZTX0pVTVAQGhIKCgZDX0ZBTEwQGxIKCgZTX0ZBTEwQHBIKCgZDX0xB",
            "TkQQHRIKCgZTX0xBTkQQHhILCgdDX1NLSUxMEB8SCwoHU19TS0lMTBAgEgkK",
            "BVNfSElUECESCgoGQ19URVNUECISCgoGU19URVNUECMSDgoKQ19KVU1QX0VO",
            "RBAkEg4KClNfSlVNUF9FTkQQJSqfAwoLQ2lwaGVyU3VpdGUSCwoHQUVTX0VD",
            "QhAAEgsKB0FFU19DQkMQARILCgdBRVNfQ0ZCEAISCwoHQUVTX09GQhADEgsK",
            "B0FFU19DVFIQBBIMCghBUklBX0VDQhAFEgwKCEFSSUFfQ0JDEAYSDAoIQVJJ",
            "QV9DRkIQBxIMCghBUklBX09GQhAIEgwKCEFSSUFfQ1RSEAkSDQoJSElHSFRf",
            "RUNCEAoSDQoJSElHSFRfQ0JDEAsSDQoJSElHSFRfQ0ZCEAwSDQoJSElHSFRf",
            "T0ZCEA0SDQoJSElHSFRfQ1RSEA4SDQoJU1BFQ0tfRUNCEA8SDQoJU1BFQ0tf",
            "Q0JDEBASDQoJU1BFQ0tfQ0ZCEBESDQoJU1BFQ0tfT0ZCEBISDQoJU1BFQ0tf",
            "Q1RSEBMSDQoJVFdJTkVfRUNCEBQSDQoJVFdJTkVfQ0JDEBUSDQoJVFdJTkVf",
            "Q0ZCEBYSDQoJVFdJTkVfT0ZCEBcSDQoJVFdJTkVfQ1RSEBgSCwoHQUVTX0dD",
            "TRAZEgwKCEFSSUFfR0NNEBoSDQoJU1BFQ0tfR0NNEBsqMAoHTW92ZURpchII",
            "CgRMRUZUEAASCQoFUklHSFQQARIGCgJVUBACEggKBERPV04QAypUCglCYXNl",
            "U3RhdGUSCAoESURMRRAAEgoKBk1PVklORxABEggKBEpVTVAQAhIICgRGQUxM",
            "EAMSCAoETEFORBAEEgkKBVNLSUxMEAUSCAoEREVBRBAGKiYKCENoYXRUeXBl",
            "EgcKA0FMTBAAEggKBFJPT00QARIHCgNNQVAQAkIbqgIYR29vZ2xlLlByb3Rv",
            "YnVmLlByb3RvY29sYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Google.Protobuf.Protocol.MsgId), typeof(global::Google.Protobuf.Protocol.CipherSuite), typeof(global::Google.Protobuf.Protocol.MoveDir), typeof(global::Google.Protobuf.Protocol.BaseState), typeof(global::Google.Protobuf.Protocol.ChatType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum MsgId {
    [pbr::OriginalName("C_HELLO")] CHello = 0,
    [pbr::OriginalName("S_HELLO")] SHello = 1,
    [pbr::OriginalName("C_HELLO_DONE")] CHelloDone = 2,
    [pbr::OriginalName("S_HELLO_DONE")] SHelloDone = 3,
    [pbr::OriginalName("C_REGISTER")] CRegister = 4,
    [pbr::OriginalName("S_REGISTER")] SRegister = 5,
    [pbr::OriginalName("C_LOGIN")] CLogin = 6,
    [pbr::OriginalName("S_LOGIN")] SLogin = 7,
    [pbr::OriginalName("C_ENTER_ROOM")] CEnterRoom = 8,
    [pbr::OriginalName("S_ENTER_ROOM")] SEnterRoom = 9,
    [pbr::OriginalName("C_ENTER_MAP")] CEnterMap = 10,
    [pbr::OriginalName("S_ENTER_MAP")] SEnterMap = 11,
    [pbr::OriginalName("S_ENTER_MAP_BROADCAST")] SEnterMapBroadcast = 12,
    [pbr::OriginalName("C_LEAVE_ROOM")] CLeaveRoom = 13,
    [pbr::OriginalName("S_LEAVE_ROOM")] SLeaveRoom = 14,
    [pbr::OriginalName("C_LEAVE_MAP")] CLeaveMap = 15,
    [pbr::OriginalName("S_LEAVE_MAP")] SLeaveMap = 16,
    [pbr::OriginalName("C_CHAT")] CChat = 17,
    [pbr::OriginalName("S_CHAT")] SChat = 18,
    [pbr::OriginalName("C_MOVE_START")] CMoveStart = 19,
    [pbr::OriginalName("S_MOVE_START")] SMoveStart = 20,
    [pbr::OriginalName("C_MOVING")] CMoving = 21,
    [pbr::OriginalName("S_MOVING")] SMoving = 22,
    [pbr::OriginalName("C_MOVE_END")] CMoveEnd = 23,
    [pbr::OriginalName("S_MOVE_END")] SMoveEnd = 24,
    [pbr::OriginalName("C_JUMP")] CJump = 25,
    [pbr::OriginalName("S_JUMP")] SJump = 26,
    [pbr::OriginalName("C_FALL")] CFall = 27,
    [pbr::OriginalName("S_FALL")] SFall = 28,
    [pbr::OriginalName("C_LAND")] CLand = 29,
    [pbr::OriginalName("S_LAND")] SLand = 30,
    [pbr::OriginalName("C_SKILL")] CSkill = 31,
    [pbr::OriginalName("S_SKILL")] SSkill = 32,
    [pbr::OriginalName("S_HIT")] SHit = 33,
    [pbr::OriginalName("C_TEST")] CTest = 34,
    [pbr::OriginalName("S_TEST")] STest = 35,
    [pbr::OriginalName("C_JUMP_END")] CJumpEnd = 36,
    [pbr::OriginalName("S_JUMP_END")] SJumpEnd = 37,
  }

  public enum CipherSuite {
    [pbr::OriginalName("AES_ECB")] AesEcb = 0,
    [pbr::OriginalName("AES_CBC")] AesCbc = 1,
    [pbr::OriginalName("AES_CFB")] AesCfb = 2,
    [pbr::OriginalName("AES_OFB")] AesOfb = 3,
    [pbr::OriginalName("AES_CTR")] AesCtr = 4,
    [pbr::OriginalName("ARIA_ECB")] AriaEcb = 5,
    [pbr::OriginalName("ARIA_CBC")] AriaCbc = 6,
    [pbr::OriginalName("ARIA_CFB")] AriaCfb = 7,
    [pbr::OriginalName("ARIA_OFB")] AriaOfb = 8,
    [pbr::OriginalName("ARIA_CTR")] AriaCtr = 9,
    [pbr::OriginalName("HIGHT_ECB")] HightEcb = 10,
    [pbr::OriginalName("HIGHT_CBC")] HightCbc = 11,
    [pbr::OriginalName("HIGHT_CFB")] HightCfb = 12,
    [pbr::OriginalName("HIGHT_OFB")] HightOfb = 13,
    [pbr::OriginalName("HIGHT_CTR")] HightCtr = 14,
    [pbr::OriginalName("SPECK_ECB")] SpeckEcb = 15,
    [pbr::OriginalName("SPECK_CBC")] SpeckCbc = 16,
    [pbr::OriginalName("SPECK_CFB")] SpeckCfb = 17,
    [pbr::OriginalName("SPECK_OFB")] SpeckOfb = 18,
    [pbr::OriginalName("SPECK_CTR")] SpeckCtr = 19,
    [pbr::OriginalName("TWINE_ECB")] TwineEcb = 20,
    [pbr::OriginalName("TWINE_CBC")] TwineCbc = 21,
    [pbr::OriginalName("TWINE_CFB")] TwineCfb = 22,
    [pbr::OriginalName("TWINE_OFB")] TwineOfb = 23,
    [pbr::OriginalName("TWINE_CTR")] TwineCtr = 24,
    [pbr::OriginalName("AES_GCM")] AesGcm = 25,
    [pbr::OriginalName("ARIA_GCM")] AriaGcm = 26,
    [pbr::OriginalName("SPECK_GCM")] SpeckGcm = 27,
  }

  public enum MoveDir {
    [pbr::OriginalName("LEFT")] Left = 0,
    [pbr::OriginalName("RIGHT")] Right = 1,
    [pbr::OriginalName("UP")] Up = 2,
    [pbr::OriginalName("DOWN")] Down = 3,
  }

  public enum BaseState {
    [pbr::OriginalName("IDLE")] Idle = 0,
    [pbr::OriginalName("MOVING")] Moving = 1,
    [pbr::OriginalName("JUMP")] Jump = 2,
    [pbr::OriginalName("FALL")] Fall = 3,
    [pbr::OriginalName("LAND")] Land = 4,
    [pbr::OriginalName("SKILL")] Skill = 5,
    [pbr::OriginalName("DEAD")] Dead = 6,
  }

  public enum ChatType {
    [pbr::OriginalName("ALL")] All = 0,
    [pbr::OriginalName("ROOM")] Room = 1,
    [pbr::OriginalName("MAP")] Map = 2,
  }

  #endregion

}

#endregion Designer generated code
